# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - acs-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests (if present)
        run: npm run test --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: . # Upload entire backend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D91C292C26774C03B22270C7287E28FA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4303E8357054DF891707FAEED3F8FA2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_714B0912DA6B4893BD7ECCEF071E3EE3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'acs-backend'
          slot-name: 'Production'
          package: .
